///POSTS
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const FETCH_POSTS_REJECTED = "FETCH_POSTS_REJECTED";
export const SEARCH_POSTS = "SEARCH_POSTS";
export const SEARCH_POSTS_SUCCESS = "SEARCH_POSTS_SUCCESS";
export const GET_POSTS_PAGE = "GET_POSTS_PAGE";
export const GET_POSTS_PAGE_SUCCESS = "GET_POSTS_PAGE_SUCCESS";
export const GET_ONE_POST = "GET_ONE_POST";
export const GET_ONE_POST_SUCCESS = "GET_ONE_POST_SUCCESS";
export const CREATE_OR_UPDATE_POST = "CREATE_POST";
export const CREATE_OR_UPDATE_POST_SUCCESS = "CREATE_OR_UPDATE_POST_SUCCESS";
export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const NEW_POST_ADDED_CLOSE_TOAST = "NEW_POST_ADDED_CLOSE_TOAST";

// AUTHORS
export const GET_ALL_AUTHORS_SUCCESS = "GET_ALL_AUTHORS_SUCCESS";
export const GET_ALL_AUTHORS = "GET_ALL_AUTHORS";
export const FETCH_AUTHORS_REJECTED = "FETCH_AUTHORS_REJECTED";
export const GET_AUTHOR_POSTS = "GET_AUTHOR_POSTS";
export const GET_AUTHOR_POSTS_SUCCESS = "GET_AUTHOR_POSTS_SUCCESS";
export const GET_ONE_AUTHOR = "GET_ONE_AUTHOR";
export const GET_ONE_AUTHOR_SUCCESS = "GET_ONE_AUTHOR_SUCCESS";
export const CLEANUP_SINGLE_AUTHOR = "CLEANUP_SINGLE_AUTHOR";

// UI

export const LOADING = "LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const HIDE_HEADER = "HIDE_HEADER";
export const SHOW_HEADER = "SHOW_HEADER";

// AUTH

export const LOGIN = "LOGIN";
export const LOGGED_IN_SUCCESS = "LOGGED_IN_SUCCESS";
